name: Build Redocly  # Based on https://github.com/jizt-it/jizt-api-spec/blob/main/make.sh
on:
  push:
    branches:
      - main
    paths:
      - code/API_definitions/*.yaml

jobs:
  build:
    runs-on: ubuntu-latest    
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Build Redocly docs
      run: ./utils/make-redocly.sh
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3 # https://github.com/peaceiris/actions-gh-pages
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        force_orphan: true
        exclude_assets: '.github,code,utils,README.md'

